my_app/tasks/models.py
from sqlalchemy.orm import relationship

from my_app.documents.models import Document

from my_app import db

task_tag = db.Table('task_tag', 
        db.Column('task_id', db.Integer, db.ForeignKey('tasks.id'),primary_key=True),
        db.Column('tag_id', db.Integer, db.ForeignKey('tags.id'),primary_key=True)
        )

class Task(db.Model):
    __tablename__ = 'tasks'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    document_id = db.Column(db.Integer, db.ForeignKey('documents.id'),
        nullable=True)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'),
        nullable=False)
    tags = relationship('Tag', secondary=task_tag, back_populates='tasks')
    category = relationship('Category')

    document = relationship('Document', lazy='joined')

    def getById(self, id: int):
        task = db.session.query(self).filter(id == id).first()
        return id

    @property
    def serialize(self):
       return {
           'id'    : self.id,
           'name'  : self.name,
           'category'  : self.category.name,
           'category_id'  : self.category_id,
       }

class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))

class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    tasks = relationship('Task', secondary=task_tag)

my_app/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, SelectField, FileField, DateField, HiddenField
from wtforms.validators import InputRequired, ValidationError

def my_length_check(form, field):
    if len(field.data) > 1:
        raise ValidationError('Field must be less than 50 characters')

def length(min=-1, max=-1):
    message = 'Must be between %d and %d characters long.' % (min, max)

    def _length(form, field):
        l = field.data and len(field.data) or 0
        if l < min and l > max:
            field.errors += (ValidationError(message=message),)
            raise ValidationError(message=message)

    return _length

class Task(FlaskForm):
    
    # name = StringField('Name', [InputRequired(), length(max=50)]) # length(max=50)]
    # name = StringField('Name', [InputRequired(), length(max=1)])
    name = StringField('Name', validators=[InputRequired(), length(max=1)]) # length(max=50)]
    # document = FileField('File') 
    # date = DateField('Date',  format='%Y-%m-%d')
    # language = SelectField('Programming Language', choices=[('cpp', 'C++'), ('py', 'Python'), ('text', 'Plain Text')])
    category = SelectField('Category',)
    # price = DecimalField('Precio', validators=[InputRequired(), NumberRange(min=Decimal('0.0'))])
    # category_id = SelectField('Categoría', coerce=int)
    file = FileField('Archivo') #, validators=[FileRequired()]

    # def validate_name(form, field):
    #     if len(field.data) > 2:
    #         raise ValidationError('Name must be less than 2 characters')


class TaskTagAdd(FlaskForm):
   tag = SelectField('Tag',)

class TaskTagRemove(FlaskForm):
   tag = HiddenField('Tag')

my_app/tasks/controllers.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required
from flask_babel import gettext

from werkzeug.utils import secure_filename

# from my_app.tasks.models import Task
from my_app import app
from my_app.tasks import forms
from my_app.tasks import models
from my_app.tasks import operations
from my_app.documents import operations as doc_operations

from my_app import config, cache

taskRoute = Blueprint('tasks',__name__, url_prefix="/tasks")

task_list =[]

@taskRoute.before_request
# @login_required
def before():
    pass


@taskRoute.route('/')
# @taskRoute.route('/<int:id>')
# @cache.cached(timeout=60)
def index(): #page:int=1 
   title = gettext('List of Task')
   operations.getAll()
   return render_template('dashboard/task/index.html', tasks=operations.pagination(request.args.get('page', 1, type=int), request.args.get('size', 10, type=int)))

@taskRoute.route('/<int:id>')
def show(id:int):
   return "Show "+ str(id)

@taskRoute.route('/delete/<int:id>')
def delete(id:int):
    task=operations.getById(id)
    operations.delete(task.id)
   #  doc_operations.delete(task.document_id)
    return redirect(url_for('tasks.index'))


@taskRoute.route('/create', methods=('GET', 'POST'))
def create():

   # form = forms.Task(csrf_enabled=False)
   form = forms.Task()
   categories = [ (c.id, c.name) for c in models.Category.query.all()]
   form.category.choices = categories
   # print(form.date.data)
   if form.validate_on_submit():
      operations.create(form.name.data, form.category.data)
      # print(config.allowed_extensions_file(form.document.data.filename))
      # if form.document.data and config.allowed_extensions_file(form.document.data.filename):
      #    print(form.document.data)
         # f = form.document.data
         # filename = secure_filename(f.filename)
         # f.save(os.path.join(
         #    app.instance_path, app.config['UPLOAD_FOLDER'], filename
         # ))
   print(form.name.errors)
   return render_template('dashboard/task/create.html', form=form)

@taskRoute.route('/update/<int:id>', methods=['GET','POST'])
def update(id:int):

   # task = operations.getById(id)   
   task = models.Task.getById(id)
   form = forms.Task()#meta={'csrf':False}
   formTag = forms.TaskTagAdd()

   categories = [ (c.id, c.name) for c in models.Category.query.all()]
   form.category.choices = categories

   tags = [ (c.id, c.name) for c in models.Tag.query.all()]
   formTag.tag.choices = tags

   if request.method == 'GET':
      form.name.data = task.name
      form.category.data = task.category_id
   
   if form.validate_on_submit():
      operations.update(id, form.name.data, form.category.data)
      flash('The registry has been updated successfully', 'info')

      f = form.file.data
      if f and config.allowed_extensions_file(f.filename):
         filename = secure_filename(f.filename)
         
         document = doc_operations.create(filename, filename.lower().rsplit('.', 1)[1], f)
         operations.update(id, form.name.data, form.category.data, document.id)
         
   return render_template('dashboard/task/update.html', form=form, formTag=formTag, formTagDelete=forms.TaskTagRemove() ,task=task, id=id)


@taskRoute.route('/<int:id>/tag/add', methods=['POST'])
def tagAdd(id:int):

   formTag = forms.TaskTagAdd()
   tags = [ (c.id, c.name) for c in models.Tag.query.all()]
   formTag.tag.choices = tags

   if formTag.validate_on_submit():
      operations.addTag(id, formTag.tag.data)

   return redirect(url_for("tasks.update",id=id))

@taskRoute.route('/<int:id>/tag/delete', methods=['POST'])
def tagRemove(id:int):
   formTag = forms.TaskTagRemove()
   if formTag.validate_on_submit():
      operations.removeTag(id, formTag.tag.data)
      
   return redirect(url_for("tasks.update",id=id))

my_app/templates/dashboard/task/create.html
{% extends "dashboard/master.html" %}

{% block head %}
{{ super() }}
<meta name="description" content="List of task">
{% endblock %}

{% block title %} List {% endblock %}

{% block content %}

<form action="{{ url_for('tasks.create') }}" method="POST" enctype="multipart/form-data">
    {{ form.name.label }}
    {{ form.name }}

    {{ form.category.label }}
    {{ form.category }}

    {{ form.csrf_token }}

    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Guardar</button>
</form>

<label for="validationServer04" class="form-label">State</label>
<select class="form-select is-invalid" required>
   <option selected disabled value="">Choose...</option>
   <option>...</option>
</select>
<div class="invalid-feedback">
   Please select a valid state.
</div>


{% if form.errors %}
<ul class="errors">
    {% for error in form.errors %}
    <li>{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}

<!-- <form action="" method="post">
    <input type="text" name="task">
    <input type="submit" value="Send">
</form> -->

{% endblock %}

my_app/templates/dashboard/task/index.html
{% extends "dashboard/master.html" %}

{% from 'macro/pagination.html' import m_pagination %}

{% block head %} 
    {{ super() }}
    <meta name="description" content="List of task">
{% endblock %}

{% block title %} List {% endblock %}

{% block content %}

<h1>{{ _('List of Task') }}</h1>

<table class="table">
    <tr>
        <td>{{ _('Id') }}</td>
        <td>{{ _('Name') }}</td>

        <td>{{ _('Obtions') }}</td>
    </tr>
    {% for t in tasks.items %}
    <tr>
        <td>
            {{ loop.index }}
        </td>
        <td>{{ t.name }}</td>
        <td>
            <a href="/tasks/update/{{ loop.index0 }}" target="_blank">Update</a>
        </td>
    </tr>
    {% endfor %}
</table>

{{ m_pagination(tasks) }}

{% endblock %}

my_app/templates/dashboard/task/update.html
{% extends "dashboard/master.html" %}


{% block title %} Update task {% endblock%}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    {{ form.name.label }}
    {{ form.name }}

    {% if id: %}
        {{ form.file.label }}
        {{ form.file }}
    {% endif %}
    
    {{ form.category.label }}
    {{ form.category }}

    {{ form.csrf_token }}

    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Guardar</button>
</form>


<h3>Document</h3>
{% if task.document: %}

    
    {% with document=task.document %}
        {% include 'dashboard/document/_detail.html'  %}
    {% endwith %}
{% endif %}

<h3>Tags</h3>
    {% include 'dashboard/task/tag/index.html' %}
    {% include 'dashboard/task/tag/assign.html' %}

{% endblock %}